### ISSUE TITLE
运行报错，麻烦大佬给看看啥原因

### ISSUE THREAD

**Issue by lovelygfj** [xhuz/replit-xray#1]
 cargo run
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 2m 09s
     Running `target/debug/replit-xray`
thread 'main' panicked at 'exec command failed, "./x": Os { code: 26, kind: ExecutableFileBusy, message: "Text file busy" }', src/server.rs:171:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
exit status 101

**Comment by lovelygfj** [comment]
大佬用了最新的更新，还是报以下的错误

warning: field `uuid` is never read
  --> src/server.rs:30:5
   |
25 | pub struct Server {
   |            ------ field in this struct
...
30 |     uuid: Option<String>,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default
   = note: `Server` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: `replit-xray` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 5m 53s
     Running `target/debug/replit-xray`
thread 'main' panicked at 'write uuid to db failed: ()', src/server.rs:163:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
exit status 101

**Comment by lovelygfj** [comment]
后来再次运行以后，出了以下log，但貌似无法连接，请大佬指点

 cargo run
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
warning: field `uuid` is never read
  --> src/server.rs:30:5
   |
25 | pub struct Server {
   |            ------ field in this struct
...
30 |     uuid: Option<String>,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default
   = note: `Server` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: `replit-xray` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 2m 05s
     Running `target/debug/replit-xray`
xxx.replit.co/c49ced89-aa87-46e5-ab07-b3ad86bfa2eb
Bad Request
Bad Request

**Comment by lovelygfj** [comment]
报告大佬，0.1.4部署没有报错，也出了密码，但用v2rayN创建新连接以后，没连上。
不知道是否有设置错误。
用的是torjan，ws协议，path是 /uuid的字符，端口443

**Comment by lovelygfj** [comment]
下载release，修改二进制程序名字不要出现xray trojan之类的东西，上传replit，增加执行权限，运行二进制即可
还请进一步说明一下，改的是哪个文件，不太懂。谢谢

**Comment by xhuz** [comment]
用v0.2.0。刚测试可以跑。正式完工了

**Comment by lovelygfj** [comment]
大佬NB，测试成功

**Comment by lovelygfj** [comment]
反馈：保活好像没起作用。
隔了一晚上第二天再连接的时候从后台看好像重新build了。
另外就是build完也被限速了。
不过我没改任何代码，直接传所有文件上去的
