### ISSUE TITLE
保活的url错误

### ISSUE THREAD

**Issue by lovelygfj** [xhuz/replit-xray#2]
脚本里是 replit.co
实际上应该是 repl.co
因此导致按照replit.co配置 和 保活均会出现错误

另外，请大佬把部署再讲得详细点行吗？
我直接建立rust，然后把文件都拖进去了，能运行成功。
但是按照首页得建立空repo，改二进制名（我改的是那个tar.gz），信件main.sh都没运行成功

**Comment by lovelygfj** [comment]
PS: 我手动改了keep_live的地址，但是貌似保活并未生效，还请大佬检查

**Comment by lovelygfj** [comment]
感谢大佬，我会部署了，原来只需要传解压出来的二进制文件即可

**Comment by xhuz** [comment]
拼写错误修复了，关闭了。
